// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdqE5Muofd7zty5HH1ky_52CB21sORnA',
    appId: '1:992421604567:web:13930dcefcff5609359492',
    messagingSenderId: '992421604567',
    projectId: 'vsesport-a5846',
    authDomain: 'vsesport-a5846.firebaseapp.com',
    storageBucket: 'vsesport-a5846.firebasestorage.app',
    measurementId: 'G-LVS2PBD65T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2zM3amTvsXz9vsZcb-RuH7-q9VL-CmtQ',
    appId: '1:992421604567:android:1744ead28995ca72359492',
    messagingSenderId: '992421604567',
    projectId: 'vsesport-a5846',
    storageBucket: 'vsesport-a5846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbfDDg0WewVlhwmIjkjIy3nj8AjATKW28',
    appId: '1:992421604567:ios:205b8d40517aee0e359492',
    messagingSenderId: '992421604567',
    projectId: 'vsesport-a5846',
    storageBucket: 'vsesport-a5846.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbfDDg0WewVlhwmIjkjIy3nj8AjATKW28',
    appId: '1:992421604567:ios:205b8d40517aee0e359492',
    messagingSenderId: '992421604567',
    projectId: 'vsesport-a5846',
    storageBucket: 'vsesport-a5846.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdqE5Muofd7zty5HH1ky_52CB21sORnA',
    appId: '1:992421604567:web:2914dba45b234379359492',
    messagingSenderId: '992421604567',
    projectId: 'vsesport-a5846',
    authDomain: 'vsesport-a5846.firebaseapp.com',
    storageBucket: 'vsesport-a5846.firebasestorage.app',
    measurementId: 'G-7DGWZW43RS',
  );
}
